- name: Instalando Apache
  yum:
    name: httpd
    state: present
- name: Iniciando Apache
  service:
    name: httpd
    state: started
    enabled: yes
- name: apache-mod
  yum:
    name: php
    state: present
- name: iniciando apache mod
  service: 
    name: httpd
    state: restarte
