- name: Instalando Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
- name: Iniciando Apache
  service:
    name: apache2
    state: started
    enabled: yes
- name: apache-mod
  apt:
    name: libapache2-mod-php
    state: present
    update_cache: yes
- name: iniciando apache mod
  service: 
    name: apache2
    state: restarted
